version: '2'
services:
  telegram-bot:
    image: artfaal/wisdomwave:$TAG
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    env_file:
      - ./.env

