name: Build and Push Docker Image

on:
  push:
    branches:
      - '*'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Set Docker tags and Deploy Path
      run: |
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        if [ "$BRANCH_NAME" == "master" ]; then
            echo "DOCKER_TAGS=artfaal/wisdomwave:master-latest" >> $GITHUB_ENV
            echo "DEPLOY_PATHS=/var/docker/compose/wisdomwave/3.5,/var/docker/compose/wisdomwave/4" >> $GITHUB_ENV
        else
            echo "DOCKER_TAGS=artfaal/wisdomwave:debug-latest" >> $GITHUB_ENV
            echo "DEPLOY_PATHS=/var/docker/compose/wisdomwave/debug" >> $GITHUB_ENV
        fi

    - name: Build and push Docker image
      uses: docker/build-push-action@v4.1.1
      with:
        push: true
        tags: ${{ env.DOCKER_TAGS }}

    - name: Deploy to server
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh/
        ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > id_rsa
        chmod 600 id_rsa
        IFS=', ' read -ra ADDR <<< "$DEPLOY_PATHS"
        for DEPLOY_DIR in "${ADDR[@]}"; do
            scp -i id_rsa update_and_rebuild.sh $SSH_USER@$SSH_HOST:$DEPLOY_DIR/
            ssh -i id_rsa $SSH_USER@$SSH_HOST "cd $DEPLOY_DIR && IMAGE_TAG=${DOCKER_TAGS##*:} ./update_and_rebuild.sh"
        done
        rm -f id_rsa
