name: Build and Push Docker Image

on:
  push:
    branches:
      - master
      - dev
      - '*'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Set Docker tags for master branch
      if: github.ref == 'refs/heads/master'
      run: echo "DOCKER_TAGS=artfaal/wisdomwave:latest,artfaal/wisdomwave:master-latest" >> $GITHUB_ENV

    - name: Set Docker tags for dev branch
      if: github.ref == 'refs/heads/dev'
      run: echo "DOCKER_TAGS=artfaal/wisdomwave:latest,artfaal/wisdomwave:dev-latest" >> $GITHUB_ENV

    - name: Set Docker tags for other branches
      if: github.ref != 'refs/heads/master' && github.ref != 'refs/heads/dev'
      run: echo "DOCKER_TAGS=artfaal/wisdomwave:latest,artfaal/wisdomwave:other-latest" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v4.1.1
      with:
        push: true
        tags: ${{ env.DOCKER_TAGS }}
